"""create search_items table

Revision ID: 108d96fe3b87
Revises: d8161989ce91
Create Date: 2025-03-30 15:51:53.792301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '108d96fe3b87'
down_revision: Union[str, None] = 'd8161989ce91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_items_content'), 'search_items', ['content'], unique=False)
    op.create_index(op.f('ix_search_items_id'), 'search_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_items_id'), table_name='search_items')
    op.drop_index(op.f('ix_search_items_content'), table_name='search_items')
    op.drop_table('search_items')
    # ### end Alembic commands ###
