"""Init auth and corpus

Revision ID: 215aec5af95c
Revises: 3e645d967db8
Create Date: 2025-05-21 18:49:22.079138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '215aec5af95c'
down_revision: Union[str, None] = '3e645d967db8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_search_items_content', table_name='search_items')
    op.drop_index('ix_search_items_id', table_name='search_items')
    op.drop_table('search_items')
    op.drop_index('ix_corpuses_id', table_name='corpuses')
    op.drop_index('ix_corpuses_name', table_name='corpuses')
    op.drop_table('corpuses')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.create_table('corpuses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_corpuses_name', 'corpuses', ['name'], unique=1)
    op.create_index('ix_corpuses_id', 'corpuses', ['id'], unique=False)
    op.create_table('search_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_search_items_id', 'search_items', ['id'], unique=False)
    op.create_index('ix_search_items_content', 'search_items', ['content'], unique=False)
    # ### end Alembic commands ###
