"""create corpus table

Revision ID: 3e645d967db8
Revises: 108d96fe3b87
Create Date: 2025-03-30 16:25:48.484931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e645d967db8'
down_revision: Union[str, None] = '108d96fe3b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corpuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corpuses_id'), 'corpuses', ['id'], unique=False)
    op.create_index(op.f('ix_corpuses_name'), 'corpuses', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_corpuses_name'), table_name='corpuses')
    op.drop_index(op.f('ix_corpuses_id'), table_name='corpuses')
    op.drop_table('corpuses')
    # ### end Alembic commands ###
